pipeline {
   agent any
   stages {
      stage("1. Clone Github url") {
         steps {
            git branch: 'main',
               url: 'https://github.com/Pascal7601/alx-backend-python.git',
               credentialsId: 'github-creds'
         }
      }
      stage("2. Install dependencies") {
         steps {
            echo "installing dependencies..."
            pip3 install -r messaging_app/requirements.txt
         }
      }
   }
}
