pipeline {
   agent any
   stages {
      stage("1. Clone Github url") {
         steps {
            git
               branch: 'main'
               url: 'https://github.com/Pascal7601/alx-backend-python.git'
         }
      }
      stage("2. Echo hello world") {
         steps {
            echo "Hello world its backend"
         }
      }
   }
}
