# Generated by Django 5.2.7 on 2025-10-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_is_edited_messagehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagehistory',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
