name: messageApp

services:
  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_started
    command: >
      sh -c "sleep 20 && python manage.py runserver 0.0.0.0:8000"

  db:
    image: mysql:8.4.6
    environment:
        MYSQL_PASSWORD: pascal
        MYSQL_USER: pascal
        MYSQL_DB: messagedb
        MYSQL_ROOT_PASSWORD: pascal
